<#
.SYNOPSIS
  DigiCode local compile-server installer (Windows PowerShell).

.DESCRIPTION
  Pulls ghcr.io/fablab-westharima/digicode-compile-api:latest, starts it on
  port 3001 with persistent named volumes, then prints the next steps.
  Docker Desktop must be installed beforehand; the script aborts with a
  download URL if it is missing.

.PARAMETER Subcommand
  install (default), update, uninstall, status, start, stop, help

.EXAMPLE
  irm https://raw.githubusercontent.com/fablab-westharima/digicode-installer/main/install.ps1 | iex

.EXAMPLE
  .\install.ps1 status

.LINK
  https://github.com/fablab-westharima/digicode-installer
#>

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('install', 'update', 'uninstall', 'status', 'start', 'stop', 'help')]
    [string]$Subcommand = 'install'
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

$Script:Image            = 'ghcr.io/fablab-westharima/digicode-compile-api:latest'
$Script:ContainerName    = 'digicode-compile-api'
$Script:Port             = 3001
$Script:InstallDir       = Join-Path $env:USERPROFILE '.digicode\compile-server'
$Script:ComposeFile      = Join-Path $Script:InstallDir 'docker-compose.yml'
$Script:HealthUrl        = "http://localhost:$($Script:Port)/health"
$Script:HealthTimeoutSec = 60

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

function Write-Info  { param([string]$Msg) Write-Host "▶ $Msg" -ForegroundColor Blue }
function Write-Ok    { param([string]$Msg) Write-Host "✅ $Msg" -ForegroundColor Green }
function Write-Warn2 { param([string]$Msg) Write-Host "⚠️  $Msg" -ForegroundColor Yellow }
function Write-Err   { param([string]$Msg) Write-Host "❌ $Msg" -ForegroundColor Red }

# ---------------------------------------------------------------------------
# Docker / Compose preflight
# ---------------------------------------------------------------------------

function Require-Docker {
    if (Get-Command docker -ErrorAction SilentlyContinue) { return }

    Write-Err "Docker not found in PATH."
    Write-Host ""
    Write-Host "DigiCode local compile-server requires Docker Desktop." -ForegroundColor Cyan
    Write-Host "Please install Docker for Windows and re-run this script:"
    Write-Host ""
    Write-Host "  • Docker Desktop for Windows" -ForegroundColor Cyan
    Write-Host "      https://www.docker.com/products/docker-desktop/"
    Write-Host "      (WSL2 backend recommended; the installer will guide you.)"
    Write-Host ""
    Write-Host "  • Alternatives (lightweight, OSS):"
    Write-Host "      - Rancher Desktop:  https://rancherdesktop.io/"
    Write-Host "      - Podman Desktop:   https://podman-desktop.io/"
    Write-Host ""
    exit 1
}

function Require-DockerRunning {
    try {
        docker info 2>$null | Out-Null
        if ($LASTEXITCODE -eq 0) { return }
    } catch {}

    Write-Err "Docker is installed but not running."
    Write-Host ""
    Write-Host "Start Docker Desktop from the Start menu, wait until the whale"
    Write-Host "icon settles, then re-run this script."
    Write-Host ""
    exit 1
}

# `docker compose` (plugin) vs the legacy `docker-compose` binary. Prefer
# the plugin, which is what every modern Docker install ships.
function Invoke-DockerCompose {
    param([Parameter(ValueFromRemainingArguments)] $Args)
    try {
        docker compose version 2>$null | Out-Null
        if ($LASTEXITCODE -eq 0) {
            & docker compose @Args
            return
        }
    } catch {}

    if (Get-Command docker-compose -ErrorAction SilentlyContinue) {
        & docker-compose @Args
        return
    }

    Write-Err "Neither 'docker compose' nor 'docker-compose' is available."
    Write-Host "Install the Docker Compose plugin (bundled with recent Docker)."
    exit 1
}

# ---------------------------------------------------------------------------
# docker-compose.yml generation
# ---------------------------------------------------------------------------

function Write-ComposeFile {
    if (-not (Test-Path $Script:InstallDir)) {
        New-Item -ItemType Directory -Force -Path $Script:InstallDir | Out-Null
    }
    $content = @"
# Generated by DigiCode local-compile installer.
# Edit at your own risk - re-running 'install' overwrites this file.
services:
  digicode-compile-api:
    image: $($Script:Image)
    container_name: $($Script:ContainerName)
    ports:
      - "$($Script:Port):$($Script:Port)"
    restart: unless-stopped
    environment:
      - PORT=$($Script:Port)
    volumes:
      - digicode-projects:/opt/digicode-compile/projects
      - digicode-cache:/opt/digicode-compile/cache
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:$($Script:Port)/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  digicode-projects:
  digicode-cache:
"@
    Set-Content -Path $Script:ComposeFile -Value $content -Encoding UTF8
}

# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

function Wait-ForHealth {
    Write-Info "Waiting for compile-server to come up (timeout $($Script:HealthTimeoutSec)s)..."
    $deadline = (Get-Date).AddSeconds($Script:HealthTimeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            $resp = Invoke-WebRequest -Uri $Script:HealthUrl -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
            if ($resp.Content -match '"status":"ok"') {
                Write-Ok "Compile-server is healthy at $($Script:HealthUrl)"
                return $true
            }
        } catch {}
        Start-Sleep -Seconds 2
        Write-Host "." -NoNewline
    }
    Write-Host ""
    Write-Err "Health check timed out after $($Script:HealthTimeoutSec)s."
    Write-Host "  Inspect logs with:  docker logs $($Script:ContainerName)"
    return $false
}

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

function Cmd-Install {
    Require-Docker
    Require-DockerRunning

    Write-Info "Writing compose file to $($Script:ComposeFile)"
    Write-ComposeFile

    Write-Info "Pulling $($Script:Image) (~1 GB compressed, ~3.8 GB extracted on first run)..."
    Invoke-DockerCompose -f $Script:ComposeFile pull

    Write-Info "Starting $($Script:ContainerName)..."
    Invoke-DockerCompose -f $Script:ComposeFile up -d

    if (-not (Wait-ForHealth)) { exit 1 }

    Write-Host ""
    Write-Ok "DigiCode local compile-server is ready."
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "  1. Open DigiCode in your browser (https://code.fablab-westharima.jp)"
    Write-Host "  2. Click the down-arrow next to the [書き込み] button"
    Write-Host "  3. Select [ローカルサーバー]"
    Write-Host ""
    Write-Host "Manage the server:" -ForegroundColor DarkGray
    Write-Host "  - Status:    .\install.ps1 status"
    Write-Host "  - Stop:      .\install.ps1 stop"
    Write-Host "  - Update:    .\install.ps1 update"
    Write-Host "  - Uninstall: .\install.ps1 uninstall"
}

function Cmd-Update {
    Require-Docker
    Require-DockerRunning
    if (-not (Test-Path $Script:ComposeFile)) {
        Write-Err "Compose file not found at $($Script:ComposeFile)."
        Write-Host "  Run '.\install.ps1 install' first."
        exit 1
    }
    Write-Info "Pulling latest image..."
    Invoke-DockerCompose -f $Script:ComposeFile pull
    Write-Info "Recreating container..."
    Invoke-DockerCompose -f $Script:ComposeFile up -d
    Wait-ForHealth | Out-Null
}

function Cmd-Uninstall {
    Require-Docker
    if (-not (Test-Path $Script:ComposeFile)) {
        Write-Warn2 "Compose file not found at $($Script:ComposeFile) - nothing to uninstall."
        return
    }

    Write-Host "This will:" -ForegroundColor Cyan
    Write-Host "  - Stop and remove the $($Script:ContainerName) container"
    Write-Host "  - Delete the persistent volumes (digicode-projects, digicode-cache)"
    Write-Host "  - Delete $($Script:InstallDir)"
    Write-Host ""
    $reply = Read-Host "Continue? [y/N]"
    if ($reply -notmatch '^(y|Y|yes|YES)$') {
        Write-Host "Cancelled."
        return
    }

    Write-Info "Stopping container and removing volumes..."
    try { Invoke-DockerCompose -f $Script:ComposeFile down -v } catch {}

    Write-Info "Removing $($Script:InstallDir)..."
    Remove-Item -Recurse -Force $Script:InstallDir -ErrorAction SilentlyContinue

    Write-Host ""
    $reply = Read-Host "Also delete the Docker image ($($Script:Image))? [y/N]"
    if ($reply -match '^(y|Y|yes|YES)$') {
        Write-Info "Removing image..."
        try { docker rmi $Script:Image } catch { Write-Warn2 "Image not found (already removed?)" }
    }

    Write-Ok "Uninstall complete."
}

function Cmd-Status {
    Require-Docker
    $names = (docker ps -a --format '{{.Names}}') -split "`n"
    if ($names -notcontains $Script:ContainerName) {
        Write-Warn2 "$($Script:ContainerName) is not installed."
        Write-Host "  Run '.\install.ps1 install' to set it up."
        return
    }

    $state = (docker inspect -f '{{.State.Status}}' $Script:ContainerName 2>$null)
    $image = (docker inspect -f '{{.Config.Image}}' $Script:ContainerName 2>$null)

    Write-Host "Container:    $($Script:ContainerName)" -ForegroundColor Cyan
    Write-Host "State:        $state"
    Write-Host "Image:        $image"
    Write-Host "Health URL:   $($Script:HealthUrl)"
    Write-Host "Compose:      $($Script:ComposeFile)"
    Write-Host ""

    if ($state -eq 'running') {
        try {
            $resp = Invoke-WebRequest -Uri $Script:HealthUrl -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
            if ($resp.Content -match '"status":"ok"') {
                Write-Ok "Health check passed."
            } else {
                Write-Warn2 "Container is running but /health is not responding (still starting?)."
            }
        } catch {
            Write-Warn2 "Container is running but /health is not responding (still starting?)."
        }
    }
}

function Cmd-Start {
    Require-Docker
    Require-DockerRunning
    if (-not (Test-Path $Script:ComposeFile)) {
        Write-Err "Compose file not found - run 'install' first."
        exit 1
    }
    Invoke-DockerCompose -f $Script:ComposeFile start
    Wait-ForHealth | Out-Null
}

function Cmd-Stop {
    Require-Docker
    if (-not (Test-Path $Script:ComposeFile)) {
        Write-Err "Compose file not found - run 'install' first."
        exit 1
    }
    Invoke-DockerCompose -f $Script:ComposeFile stop
    Write-Ok "Stopped."
}

function Cmd-Help {
    Write-Host @"
DigiCode local compile-server installer

Usage: .\install.ps1 [subcommand]

Subcommands:
  install     Pull the image, generate compose file, start the container,
              then verify /health (default if no subcommand given)
  update      Pull the latest image and recreate the container
  uninstall   Stop the container, remove volumes and install dir
              (asks before deleting the image)
  status      Show container state, image, and a live health check
  start       Start an existing (stopped) container
  stop        Stop the container without removing it
  help        Show this message

Install dir:    $($Script:InstallDir)
Image:          $($Script:Image)
Health URL:     $($Script:HealthUrl)

Docs (5 langs): https://code.fablab-westharima.jp/docs/local-compile-server
"@ -ForegroundColor Cyan
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

switch ($Subcommand) {
    'install'   { Cmd-Install }
    'update'    { Cmd-Update }
    'uninstall' { Cmd-Uninstall }
    'status'    { Cmd-Status }
    'start'     { Cmd-Start }
    'stop'      { Cmd-Stop }
    'help'      { Cmd-Help }
}
